server:
  port: ${PORT:8080}

spring:
  application:
    name: student-microservice

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
