apiVersion: v1
kind: Service
metadata:
  name: rosario-service
  namespace: rosario-namespace
spec:
  selector:
    app: rosario-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: container-port
      port: 8087
      targetPort: 8087
      protocol: TCP
  type: ClusterIP